
export const Headertext={
    BecomeaWomeynPreneurs:"Become a WomeynPreneurs",
    MyProfile:"My Profile",
    ProductOrders:"Product Orders",
    ServiceOrders:" Service Orders",
    Whishlist:" Whishlist",
    Coupons:"Coupons",
    FAQ:"FAQ",
    Logout:"Logout",
    CreateaccountLogIn:" Create account / LogIn",
    LogInSignUp:" LogIn/SignUp",
    Explore:"Explore",
    Products:"Products",
    Services:"Services",
    Products:"Products",
    Services:"Services",
    OurWomeynPreneurs:"Our WomeynPreneurs",
    EventsBlogs:"Events & Blogs",
    WhatisWomeyn:"What is Womeyn",
    OurMissionVision:" Our Mission & Vision",
    TheLogoSignificance:" The Logo Significance",
    OurTeam:"Our Team",
    PartnersCollaborations:"Partners & Collaborations",
    JoinWomeyn:"Join Womeyn",
    GetInTouch:"Get In Touch",
    AboutUs:"About Us",
    Login:"Login"
}