
// SLIDER COUNT TYPES START
export const LOADING_WOMEN_SLIDER = "LOADING_WOMEN_SLIDER";
export const GETDATA_WOMEN_SLIDER = "GETDATA_WOMEN_SLIDER";
export const ERROR_WOMEN_SLIDER = "ERROR_WOMEN_SLIDER";
// SLIDER COUNT TYPES END

// LOGIN TYPES START

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

// LOGIN TYPES END



// LOGIN TYPES START

export const THEME_LOADING = "THEME_LOADING";
export const THEME_SUCCESS = "THEME_SUCCESS";
export const THEME_ERROR = "THEME_ERROR";

// LOGIN TYPES END


// LOGIN TYPES START

export const CART_LOADING = "CART_LOADING";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_DELETE = "CART_DELETE";
export const CART_ALL_DELETE="CART_ALL_DELETE";

// LOGIN TYPES END


// aboutus count sections


export const LOADING_WOMEN_SLIDER1 = "LOADING_WOMEN_SLIDER1";
export const GETDATA_WOMEN_SLIDER1 = "GETDATA_WOMEN_SLIDER1";
export const ERROR_WOMEN_SLIDER1 = "ERROR_WOMEN_SLIDER1";